spring.application.name=bpr-flavors-hub

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# DATABASE
# ===============================
# ===============================
# DATABASE
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# ===============================
# CONNECTION POOL
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
# ==========================
# SECURITY LOGGING
# ==========================
logging.level.org.springframework.security=INFO